fail_fast: false
exclude: 'external'
repos:
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        always_run: false
        files: '.*\.(cpp|hpp|cu|cuh)'
        exclude: '^libs/'
        args: ["-i", "-style=file"]

    -   id: cmake-format
        name: cmake-format
        entry: cmake-format
        language: system
        always_run: false
        files: 'CMakeLists.txt'
        args: ["-i"]
